--구구단중 5단을 출력하시오.

DECLARE
	FIVE NUMBER;
BEGIN
 FIVE := 1;
	DBMS_OUTPUT.PUT_LINE('BASIC LOOP');
 LOOP
	DBMS_OUTPUT.PUT(5 *  FIVE );
	DBMS_OUTPUT.PUT( chr(9) );

	IF FIVE < 10 THEN
 FIVE := FIVE +1;
		END IF;
	EXIT WHEN FIVE =10; 
	END LOOP;
	DBMS_OUTPUT.NEW_LINE();

	DBMS_OUTPUT.PUT_LINE('WHILE LOOP');
  FIVE := 1;
	WHILE FIVE <= 9 LOOP
	DBMS_OUTPUT.PUT(5 *  FIVE);
	DBMS_OUTPUT.PUT( chr(9) );

	FIVE := FIVE+1;
END LOOP;
	DBMS_OUTPUT.NEW_LINE();

	DBMS_OUTPUT.PUT_LINE('FOR LOOP');
FOR FIVE2 IN 1..9 LOOP
	DBMS_OUTPUT.PUT(5 * FIVE2);
	DBMS_OUTPUT.PUT( chr(9) );

END LOOP;
	DBMS_OUTPUT.NEW_LINE();

END;
/

